### ISSUE TITLE
NIV Headers + Additional Options

### ISSUE THREAD

**Issue by swt83** [Bohooslav/bain#40]
Thank you for this, very much appreciated.  I'm reading the NIV84 and the summary / topic headers are merged into the verses and it makes reading a little difficult.  Could you separate the headers by putting them in bold, make them appear on their own line, and add an option to remove them?  Also would like an option to hide verse numbers, if possible.
![example2](https://user-images.githubusercontent.com/907900/132134162-95fa0351-0de6-41fd-a07a-f54dad76cdbc.png)

**Comment by Bohooslav** [comment]
Hi Scott 👋🏻

Sadly, I can do nothing with those headers. Such is the translation. I myself prefer to read YLT translation.
But, I can easily add an option for hiding the verse number.

Thank you for becoming a patron. I will update the app soon with verse hiding option.
